title: Ferramentas Digitais e a Pesquisa em Humanidades
logo: LOGO-HISTÓRIA-BA-novo.png
description: Site da disciplina optativa mins=istrada por Eric Brasil no Período Letivo Excepcional, IHL-UNILAB.
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
