title: Ferramentas Digitais e a Pesquisa em Humanidades
logo: docs/LOGO-HISTÓRIA-BA-novo.png
description: Site da disciplina optativa Ferramentas Digitais e a Pesquisa em Humanidades, IHL-UNILAB.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal