title: Ferramentas Digitais e a Pesquisa em Humanidades
logo: https://github.com/ericbrasiln/ferramentas_digitais_UNILAB/docs/LOGO-HISTÓRIA-BA-novo.png
description: Site da disciplina optativa Ferramentas Digitais e a Pesquisa em Humanidades, IHL-UNILAB.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
